//
//  DataModels.swift
//  Quotes
//
//  Created by Afnan Ahmed on 12/12/2023.
//

import Foundation
import UIKit
struct QuotesData {
   
    var title : String
    var Quotes : [QuotesNote]
    
    init(Title: String, Notes: [QuotesNote]) {
        self.title = Title
        self.Quotes = Notes
    }

}

struct QuotesNote {
    var titel : String
    var description : String
    var favoriote : Bool = true

    init(titel: String, descrip: String, Favo: Bool) {
        self.titel = titel
        self.description = descrip
        self.favoriote = Favo
    }
    
}

var AppsQoutes: [QuotesNote] = [
    
    QuotesNote(titel: "Love", descrip: "Love is not about how many days, months, or years you have been together. It's about how much you love each other every single day.", Favo: false),
    QuotesNote(titel: "Love", descrip: "The best love is the kind that awakens the soul; that makes us reach for more, that plants the fire in our hearts and brings peace to our minds.", Favo: false),
    QuotesNote(titel: "Love", descrip: "To love and be loved is to feel the sun from both sides.", Favo: false),
    QuotesNote(titel: "Love", descrip: "Love is when the other person's happiness is more important than your own.", Favo: false),
    QuotesNote(titel: "Love", descrip: "In the arithmetic of love, one plus one equals everything, and two minus one equals nothing.", Favo: false),
    QuotesNote(titel: "Love", descrip: "Love is a game that two can play and both can win.", Favo: false),
    QuotesNote(titel: "Love", descrip: "A flower cannot blossom without sunshine, and man cannot live without love.", Favo: false),
    QuotesNote(titel: "Love", descrip: "Love is an endless mystery, for it has nothing else to explain it.", Favo: false),
    QuotesNote(titel: "Love", descrip: "Love is the master key that opens the gates of happiness.", Favo: false),
    QuotesNote(titel: "Love", descrip: "The greatest happiness you can have is knowing that you are loved for who you are.", Favo: false),
    QuotesNote(titel: "Love", descrip: "Love is like the wind; you can't see it, but you can feel it.", Favo: false),
    QuotesNote(titel: "Love", descrip: "The best proof of love is trust.", Favo: false),
    QuotesNote(titel: "Love", descrip: "Love is the only force capable of transforming an enemy into a friend.", Favo: false),
    QuotesNote(titel: "Love", descrip: "Life without love is like a tree without blossoms or fruit.", Favo: false),
    QuotesNote(titel: "Love", descrip: "Love doesn't make the world go 'round. Love is what makes the ride worthwhile.", Favo: false),
    QuotesNote(titel: "Motivational", descrip: "Your time is limited, don't waste it living someone else's life.", Favo: false),
    QuotesNote(titel: "Motivational", descrip: "Success is not final, failure is not fatal: It is the courage to continue that counts.", Favo: false),
    QuotesNote(titel: "Motivational", descrip: "The only way to do great work is to love what you do.", Favo: false),
    QuotesNote(titel: "Motivational", descrip: "Don't watch the clock; do what it does. Keep going.", Favo: false),
    QuotesNote(titel: "Motivational", descrip: "You are never too old to set another goal or to dream a new dream.", Favo: false),
    QuotesNote(titel: "Motivational", descrip: "Believe you can, and you're halfway there.", Favo: false),
    QuotesNote(titel: "Motivational", descrip: "The only place where success comes before work is in the dictionary.", Favo: false),
    QuotesNote(titel: "Motivational", descrip: "Success is not in what you have, but who you are.", Favo: false),
    QuotesNote(titel: "Motivational", descrip: "Your attitude determines your direction.", Favo: false),
    QuotesNote(titel: "Motivational", descrip: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", Favo: false),
    QuotesNote(titel: "Motivational", descrip: "The future belongs to those who believe in the beauty of their dreams.", Favo: false),
    QuotesNote(titel: "Motivational", descrip: "The only person you are destined to become is the person you decide to be.", Favo: false),
    QuotesNote(titel: "Motivational", descrip: "You are what you do, not what you say you'll do.", Favo: false),
    QuotesNote(titel: "Motivational", descrip: "The secret of getting ahead is getting started.", Favo: false),
    QuotesNote(titel: "Motivational", descrip: "It's not about the destination, it's about the journey.", Favo: false),
    QuotesNote(titel: "Inspiration", descrip: "Your time is limited, don't waste it living someone else's life.", Favo: false),
    QuotesNote(titel: "Inspiration", descrip: "Believe you can, and you're halfway there.", Favo: false),
    QuotesNote(titel: "Inspiration", descrip: "The only way to do great work is to love what you do.", Favo: false),
    QuotesNote(titel: "Inspiration", descrip: "The best way to predict the future is to create it.", Favo: false),
    QuotesNote(titel: "Inspiration", descrip: "Life is either a daring adventure or nothing at all.", Favo: false),
    QuotesNote(titel: "Inspiration", descrip: "To live is the rarest thing in the world. Most people exist, that is all.", Favo: false),
    QuotesNote(titel: "Inspiration", descrip: "The only impossible journey is the one you never begin.", Favo: false),
    QuotesNote(titel: "Inspiration", descrip: "It's not about the destination, it's about the journey.", Favo: false),
    QuotesNote(titel: "Inspiration", descrip: "The purpose of our lives is to be happy.", Favo: false),
    QuotesNote(titel: "Inspiration", descrip: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", Favo: false),
    QuotesNote(titel: "Inspiration", descrip: "The greatest glory in living lies not in never falling, but in rising every time we fall.", Favo: false),
    QuotesNote(titel: "Inspiration", descrip: "Life is short, and it's up to you to make it sweet.", Favo: false),
    QuotesNote(titel: "Inspiration", descrip: "You have within you, right now, everything you need to deal with whatever the world can throw at you.", Favo: false),
    QuotesNote(titel: "Inspiration", descrip: "The journey of a thousand miles begins with one step.", Favo: false),
    QuotesNote(titel: "Inspiration", descrip: "Do not wait to strike till the iron is hot, but make it hot by striking.", Favo: false),
    QuotesNote(titel: "Wisdom", descrip: "The only true wisdom is in knowing you know nothing.", Favo: false),
    QuotesNote(titel: "Wisdom", descrip: "The more I learn, the more I realize how much I don't know.", Favo: false),
    QuotesNote(titel: "Wisdom", descrip: "Knowledge speaks, but wisdom listens.", Favo: false),
    QuotesNote(titel: "Wisdom", descrip: "Wisdom is not a product of schooling but of the lifelong attempt to acquire it.", Favo: false),
    QuotesNote(titel: "Wisdom", descrip: "The only thing we have to fear is fear itself.", Favo: false),
    QuotesNote(titel: "Wisdom", descrip: "The best revenge is to be unlike him who performed the injustice.", Favo: false),
    QuotesNote(titel: "Wisdom", descrip: "In three words I can sum up everything I've learned about life: It goes on.", Favo: false),
    QuotesNote(titel: "Wisdom", descrip: "If you want to lift yourself up, lift up someone else.", Favo: false),
    QuotesNote(titel: "Wisdom", descrip: "The roots of education are bitter, but the fruit is sweet.", Favo: false),
    QuotesNote(titel: "Wisdom", descrip: "Life is 10% what happens to us and 90% how we react to it.", Favo: false),
    QuotesNote(titel: "Wisdom", descrip: "If you are depressed, you are living in the past. If you are anxious, you are living in the future. If you are at peace, you are living in the present.", Favo: false),
    QuotesNote(titel: "Wisdom", descrip: "What you get by achieving your goals is not as important as what you become by achieving your goals.", Favo: false),
    QuotesNote(titel: "Wisdom", descrip: "The only place where success comes before work is in the dictionary.", Favo: false),
    QuotesNote(titel: "Wisdom", descrip: "If you want to go fast, go alone. If you want to go far, go together.", Favo: false),
    QuotesNote(titel: "Wisdom", descrip: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", Favo: false),
    QuotesNote(titel: "Humor", descrip: "I'm writing a book. I've got the page numbers done.", Favo: false),
    QuotesNote(titel: "Humor", descrip: "Common sense is like deodorant. The people who need it most never use it.", Favo: false),
    QuotesNote(titel: "Humor", descrip: "I told my wife she was drawing her eyebrows too high. She looked surprised.", Favo: false),
    QuotesNote(titel: "Humor", descrip: "I'm on a whiskey diet. I've lost three days already.", Favo: false),
    QuotesNote(titel: "Humor", descrip: "I'm not lazy; I'm in energy-saving mode.", Favo: false),
    QuotesNote(titel: "Humor", descrip: "Why do they call it rush hour when nothing moves?", Favo: false),
    QuotesNote(titel: "Humor", descrip: "I used to be a baker because I kneaded dough.", Favo: false),
    QuotesNote(titel: "Humor", descrip: "If at first, you don't succeed, then skydiving definitely isn't for you.", Favo: false),
    QuotesNote(titel: "Humor", descrip: "I'm not arguing, I'm just explaining why I'm right.", Favo: false),
    QuotesNote(titel: "Humor", descrip: "I'm on a seafood diet. I see food and I eat it.", Favo: false),
    QuotesNote(titel: "Humor", descrip: "My wife told me to stop impersonating a flamingo. I had to put my foot down.", Favo: false),
    QuotesNote(titel: "Humor", descrip: "I'm reading a book on anti-gravity. It's impossible to put down!", Favo: false),
    QuotesNote(titel: "Humor", descrip: "Why did the scarecrow win an award? Because he was outstanding in his field!", Favo: false),
    QuotesNote(titel: "Humor", descrip: "I'm not clumsy; I'm just on a mission to find the floor.", Favo: false),
    QuotesNote(titel: "Humor", descrip: "I used to play piano by ear, but now I use my hands.", Favo: false),
    QuotesNote(titel: "Friendship", descrip: "A real friend is one who walks in when the rest of the world walks out.", Favo: false),
    QuotesNote(titel: "Friendship", descrip: "Friendship is born at that moment when one person says to another, 'What! You too? I thought I was the only one.'", Favo: false),
    QuotesNote(titel: "Friendship", descrip: "True friendship comes when the silence between two people is comfortable.", Favo: false),
    QuotesNote(titel: "Friendship", descrip: "Friendship is the only cement that will ever hold the world together.", Favo: false),
    QuotesNote(titel: "Friendship", descrip: "A friend is someone who knows all about you and still loves you.", Favo: false),
    QuotesNote(titel: "Friendship", descrip: "Friendship is born at that moment when one person says to another, 'What! You too? I thought I was the only one.'", Favo: false),
    QuotesNote(titel: "Friendship", descrip: "A friend is one of the nicest things you can have and one of the best things you can be.", Favo: false),
    QuotesNote(titel: "Friendship", descrip: "A friend is someone who gives you total freedom to be yourself.", Favo: false),
    QuotesNote(titel: "Friendship", descrip: "Friendship is the inexpressible comfort of feeling safe with a person, having neither to weigh thoughts nor measure words.", Favo: false),
    QuotesNote(titel: "Friendship", descrip: "A real friend is someone you can count on no matter what, through the highs and lows.", Favo: false),
    QuotesNote(titel: "Friendship", descrip: "Friendship is the golden thread that ties the heart of all the world.", Favo: false),
    QuotesNote(titel: "Friendship", descrip: "A friend is someone who understands your past, believes in your future, and accepts you just the way you are.", Favo: false),
    QuotesNote(titel: "Friendship", descrip: "True friends are like diamonds – bright, beautiful, valuable, and always in style.", Favo: false),
    QuotesNote(titel: "Friendship", descrip: "Friendship is the only cement that will ever hold the world together.", Favo: false),
    QuotesNote(titel: "Friendship", descrip: "A friend is what the heart needs all the time.", Favo: false),
    QuotesNote(titel: "Happiness", descrip: "The greatest happiness you can have is knowing that you do not necessarily require happiness.", Favo: false),
    QuotesNote(titel: "Happiness", descrip: "Happiness is not something ready made. It comes from your own actions.", Favo: false),
    QuotesNote(titel: "Happiness", descrip: "The purpose of our lives is to be happy.", Favo: false),
    QuotesNote(titel: "Happiness", descrip: "Happiness is a choice that requires effort at times.", Favo: false),
    QuotesNote(titel: "Happiness", descrip: "Count your age by friends, not years. Count your life by smiles, not tears.", Favo: false),
    QuotesNote(titel: "Happiness", descrip: "The best way to cheer yourself is to try to cheer someone else up.", Favo: false),
    QuotesNote(titel: "Happiness", descrip: "The only thing that will make you happy is being happy with who you are.", Favo: false),
    QuotesNote(titel: "Happiness", descrip: "Happiness is when what you think, what you say, and what you do are in harmony.", Favo: false),
    QuotesNote(titel: "Happiness", descrip: "The secret of happiness is not in doing what one likes, but in liking what one does.", Favo: false),
    QuotesNote(titel: "Happiness", descrip: "Happiness is not in the mere possession of money; it lies in the joy of achievement, in the thrill of creative effort.", Favo: false),
    QuotesNote(titel: "Happiness", descrip: "The grand essentials of happiness are: something to do, something to love, and something to hope for.", Favo: false),
    QuotesNote(titel: "Happiness", descrip: "Happiness is not by chance, but by choice.", Favo: false),
    QuotesNote(titel: "Happiness", descrip: "There is only one happiness in this life, to love and be loved", Favo: false),
    QuotesNote(titel: "Happiness", descrip: "Happiness is a butterfly, which when pursued, is always just beyond your grasp, but which, if you will sit down quietly, may alight upon you.", Favo: false),
    QuotesNote(titel: "Happiness", descrip: "Happiness is the art of never holding in your mind the memory of any unpleasant thing that has passed.", Favo: false),
    QuotesNote(titel: "Creativity", descrip: "Creativity is intelligence having fun.", Favo: false),
    QuotesNote(titel: "Creativity", descrip: "Every artist was first an amateur.", Favo: false),
    QuotesNote(titel: "Creativity", descrip: "The desire to create is one of the deepest yearnings of the human soul.", Favo: false),
    QuotesNote(titel: "Creativity", descrip: "Creativity is contagious, pass it on.", Favo: false),
    QuotesNote(titel: "Creativity", descrip: "Imagination is more important than knowledge.", Favo: false),
    QuotesNote(titel: "Creativity", descrip: "Creativity takes courage.", Favo: false),
    QuotesNote(titel: "Creativity", descrip: "You can't use up creativity. The more you use, the more you have.", Favo: false),
    QuotesNote(titel: "Creativity", descrip: "The worst enemy to creativity is self-doubt.", Favo: false),
    QuotesNote(titel: "Creativity", descrip: "Creativity is the power to connect the seemingly unconnected.", Favo: false),
    QuotesNote(titel: "Creativity", descrip: "To be creative means to be in love with life.", Favo: false),
    QuotesNote(titel: "Creativity", descrip: "Art is the most beautiful of all lies.", Favo: false),
    QuotesNote(titel: "Creativity", descrip: "Creativity is inventing, experimenting, growing, taking risks, breaking rules, making mistakes, and having fun.The creative adult is the child who survived.", Favo: false),
    QuotesNote(titel: "Creativity", descrip: "In every work of genius, we recognize our own rejected thoughts.", Favo: false),
    QuotesNote(titel: "Creativity", descrip: "Creativity is allowing yourself to make mistakes. Art is knowing which ones to keep.", Favo: false),
    QuotesNote(titel: "Creativity", descrip: "Creativity is intelligence having fun.", Favo: false),
    QuotesNote(titel: "Reflection", descrip: "The unexamined life is not worth living.", Favo: false),
    QuotesNote(titel: "Reflection", descrip: "Life can only be understood backward, but it must be lived forwards.", Favo: false),
    QuotesNote(titel: "Reflection", descrip: "The only thing we have to fear is fear itself.", Favo: false),
    QuotesNote(titel: "Reflection", descrip: "An unexamined life is not a life worth living.", Favo: false),
    QuotesNote(titel: "Reflection", descrip: "Reflect upon your present blessings, of which every man has plenty; not on your past misfortunes, of which all men have some.", Favo: false),
    QuotesNote(titel: "Reflection", descrip: "Your life does not get better by chance; it gets better by change.", Favo: false),
    QuotesNote(titel: "Reflection", descrip: "We do not learn from experience... we learn from reflecting on experience.", Favo: false),
    QuotesNote(titel: "Reflection", descrip: "The greatest glory in living lies not in never falling, but in rising every time we fall.", Favo: false),
    QuotesNote(titel: "Reflection", descrip: "We can complain because rose bushes have thorns, or rejoice because thorns have roses.", Favo: false),
    QuotesNote(titel: "Reflection", descrip: "The only person you are destined to become is the person you decide to be.", Favo: false),
    QuotesNote(titel: "Reflection", descrip: "To live is the rarest thing in the world. Most people exist, that is all.", Favo: false),
    QuotesNote(titel: "Reflection", descrip: "The unexamined life is not a life worth living.", Favo: false),
    QuotesNote(titel: "Reflection", descrip: "Look well into thyself; there is a source of strength that will always spring up if thou wilt always look.", Favo: false),
    QuotesNote(titel: "Reflection", descrip: "The only limits you have are the limits you believe.", Favo: false),
    QuotesNote(titel: "Reflection", descrip: "Self-reflection is the school of wisdom.", Favo: false),
    QuotesNote(titel: "Perseverance", descrip: "It's not that I'm so smart, it's just that I stay with problems longer.", Favo: false),
    QuotesNote(titel: "Perseverance", descrip: "Perseverance is not a long race; it's many short races one after the other.", Favo: false),
    QuotesNote(titel: "Perseverance", descrip: "The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack in will.", Favo: false),
    QuotesNote(titel: "Perseverance", descrip: "It's not whether you get knocked down, it's whether you get up.", Favo: false),
    QuotesNote(titel: "Perseverance", descrip: "Success is stumbling from failure to failure with no loss of enthusiasm.", Favo: false),
    QuotesNote(titel: "Perseverance", descrip: "Perseverance is not just the ability to persist but the ability to start over.", Favo: false),
    QuotesNote(titel: "Perseverance", descrip: "Our greatest glory is not in never falling, but in rising every time we fall.", Favo: false),
    QuotesNote(titel: "Perseverance", descrip: "Perseverance is not an long race; it's many short races one after another.", Favo: false),
    QuotesNote(titel: "Perseverance", descrip: "I am not a product of my circumstances. I am a product of my decisions.", Favo: false),
    QuotesNote(titel: "Perseverance", descrip: "The only way to do great work is to love what you do.", Favo: false),
    QuotesNote(titel: "Perseverance", descrip: "Perseverance is not the absence of adversity but the presence of courage in the face of adversity.", Favo: false),
    QuotesNote(titel: "Perseverance", descrip: "Fall seven times, stand up eight.", Favo: false),
    QuotesNote(titel: "Perseverance", descrip: "Perseverance is not a character trait; it's a muscle that needs to be exercised.", Favo: false),
    QuotesNote(titel: "Perseverance", descrip: "The only limit to our realization of tomorrow will be our doubts of today.", Favo: false),
    QuotesNote(titel: "Perseverance", descrip: "Perseverance is not a passive submission to circumstances—it's a decision to move forward despite them.", Favo: false),
    QuotesNote(titel: "Humanity", descrip: "The best way to find yourself is to lose yourself in the service of others.", Favo: false),
    QuotesNote(titel: "Humanity", descrip: "You must be the change you wish to see in the world.", Favo: false),
    QuotesNote(titel: "Humanity", descrip: "The greatest glory in living lies not in never falling, but in rising every time we fall.", Favo: false),
    QuotesNote(titel: "Humanity", descrip: "To deny people their human rights is to challenge their very humanity.", Favo: false),
    QuotesNote(titel: "Humanity", descrip: "The simplest acts of kindness are by far more powerful than a thousand heads bowing in prayer.", Favo: false),
    QuotesNote(titel: "Humanity", descrip: "We can complain because rose bushes have thorns, or rejoice because thorns have roses.", Favo: false),
    QuotesNote(titel: "Humanity", descrip: "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart.", Favo: false),
    QuotesNote(titel: "Humanity", descrip: "We rise by lifting others.", Favo: false),
    QuotesNote(titel: "Humanity", descrip: "The purpose of human life is to serve, and to show compassion and the will to help others.", Favo: false),
    QuotesNote(titel: "Humanity", descrip: "The only way to do great work is to love what you do.", Favo: false),
    QuotesNote(titel: "Humanity", descrip: "It is not our differences that divide us. It is our inability to recognize, accept, and celebrate those differences.", Favo: false),
    QuotesNote(titel: "Humanity", descrip: "The measure of a country's greatness is its ability to retain compassion in times of crisis.", Favo: false),
    QuotesNote(titel: "Humanity", descrip: "Be a good human being, a warm-hearted, affectionate person. That is my fundamental belief.", Favo: false),
    QuotesNote(titel: "Humanity", descrip: "The true measure of any society can be found in how it treats its most vulnerable members.", Favo: false),
    
    QuotesNote(titel: "Nature", descrip: "Look deep into nature, and then you will understand everything better.", Favo: false),
    QuotesNote(titel: "Nature", descrip: "The clearest way into the Universe is through a forest wilderness.", Favo: false),
    QuotesNote(titel: "Nature", descrip: "Nature always wears the colors of the spirit.", Favo: false),
    QuotesNote(titel: "Nature", descrip: "Adopt the pace of nature: her secret is patience.", Favo: false),
    QuotesNote(titel: "Nature", descrip: "The poetry of the earth is never dead.", Favo: false),
    QuotesNote(titel: "Nature", descrip: "Nature does not hurry, yet everything is accomplished.", Favo: false),
    QuotesNote(titel: "Nature", descrip: "The earth has music for those who listen.", Favo: false),
    QuotesNote(titel: "Nature", descrip: "Study nature, love nature, stay close to nature. It will never fail you.", Favo: false),
    QuotesNote(titel: "Nature", descrip: "Nature is not a place to visit. It is home.", Favo: false),
    QuotesNote(titel: "Nature", descrip: "In every walk with nature, one receives far more than he seeks.", Favo: false),
    QuotesNote(titel: "Nature", descrip: "Nature is pleased with simplicity.", Favo: false),
    QuotesNote(titel: "Nature", descrip: "Nature is the art of God.", Favo: false),
    QuotesNote(titel: "Nature", descrip: "The more clearly we can focus our attention on the wonders and realities of the universe about us, the less taste we shall have for destruction.", Favo: false),
    QuotesNote(titel: "Nature", descrip: "Nature is not our enemy, to be raped and conquered. Nature is ourselves, to be cherished and explored.", Favo: false),
    QuotesNote(titel: "Nature", descrip: "To sit in the shade on a fine day and look upon the verdant green hills is the most perfect refreshment.", Favo: false),
    
    QuotesNote(titel: "Technology", descrip: "The advance of technology is based on making it fit in so that you don't really even notice it, so it's part of everyday life.", Favo: false),
    QuotesNote(titel: "Technology", descrip: "Technology is just a tool. In terms of getting the kids working together and motivating them, the teacher is the most important.", Favo: false),
    QuotesNote(titel: "Technology", descrip: "The technology you use impresses no one. The experience you create with it is everything.", Favo: false),
    QuotesNote(titel: "Technology", descrip: "The most important thing is to be able to think what you want, not to say what you want.", Favo: false),
    QuotesNote(titel: "Technology", descrip: "The art challenges the technology, and the technology inspires the art.", Favo: false),
    QuotesNote(titel: "Technology", descrip: "It has become appallingly obvious that our technology has exceeded our humanity.", Favo: false),
    QuotesNote(titel: "Technology", descrip: "The Internet is becoming the town square for the global village of tomorrow.", Favo: false),
    QuotesNote(titel: "Technology", descrip: "Any sufficiently advanced technology is indistinguishable from magic.", Favo: false),
    QuotesNote(titel: "Technology", descrip: "The great myth of our times is that technology is communication.", Favo: false),
    QuotesNote(titel: "Technology", descrip: "The technology we use alters the way we live our lives.", Favo: false),
    QuotesNote(titel: "Technology", descrip: "Technology is nothing. What's important is that you have faith in people, that they're basically good and smart, and if you give them tools, they'll do wonderful things with them.", Favo: false),
    QuotesNote(titel: "Technology", descrip: "The science of today is the technology of tomorrow.", Favo: false),
    QuotesNote(titel: "Technology", descrip: "The best way to predict the future is to invent it.", Favo: false),
    QuotesNote(titel: "Technology", descrip: "Technology is a useful servant but a dangerous master.", Favo: false),
    
    QuotesNote(titel: "Adventure", descrip: "Adventure is worthwhile in itself.", Favo: false),
    QuotesNote(titel: "Adventure", descrip: "Life is either a daring adventure or nothing at all.", Favo: false),
    QuotesNote(titel: "Adventure", descrip: "Adventure is not outside man; it is within.", Favo: false),
    QuotesNote(titel: "Adventure", descrip: "The biggest adventure you can take is to live the life of your dreams.", Favo: false),
    QuotesNote(titel: "Adventure", descrip: "Adventure is allowing the unexpected to happen to you.", Favo: false),
    QuotesNote(titel: "Adventure", descrip: "Every man's life ends the same way. It is only the details of how he lived and how he died that distinguish one man from another.", Favo: false),
    QuotesNote(titel: "Adventure", descrip: "Adventure is an attitude that we must apply to the day to day obstacles in life.", Favo: false),
    QuotesNote(titel: "Adventure", descrip: "To live would be an awfully big adventure.", Favo: false),
    QuotesNote(titel: "Adventure", descrip: "Adventure is the spice of life.", Favo: false),
    QuotesNote(titel: "Adventure", descrip: "Adventure is a path. Real adventure – self-determined, self-motivated, often risky – forces you to have firsthand encounters with the world.", Favo: false),
    QuotesNote(titel: "Adventure", descrip: "Adventure isn't hanging on a rope off the side of a mountain. Adventure is an attitude that we must apply to the day to day obstacles of life.", Favo: false),
    QuotesNote(titel: "Adventure", descrip: "Do not follow where the path may lead. Go instead where there is no path and leave a trail.", Favo: false),
    QuotesNote(titel: "Adventure", descrip: "Adventure is an attitude of the spirit.", Favo: false),
    QuotesNote(titel: "Adventure", descrip: "One way to get the most out of life is to look upon it as an adventure.", Favo: false),
    QuotesNote(titel: "Adventure", descrip: "Adventure should be part of everyone’s life. It is the whole difference between being fully alive and just existing.", Favo: false),
    QuotesNote(titel: "Technology", descrip: "The real danger is not that computers will begin to think like men, but that men will begin to think like computers.", Favo: false),
    QuotesNote(titel: "Humanity", descrip: "We are all different, which is great because we are all unique. Without diversity, life would be very boring.", Favo: false)
    
    
]

var data = [QuotesNote]()
